VkApp.Web/Models/ApplicationsView.cs
using System.Collections.Generic;
using VkApp.Data.Model;

namespace VkApp.Web.Models
{
    public class ApplicationView
    {
        public virtual int Id { get; set; }
        public virtual string Name { get; set; }
    }

    public class ApplicationsView
    {
        public IEnumerable<ApplicationView> Applications { get; set; }
        public ApplicationView NewApplication { get; set; }
        public string Error { get; set; }
    }

    public static class ApplicationMapper
    {
        public static ApplicationView Map(this Application application)
        {
            return new ApplicationView
            {
                Id = application.VkAppId,
                Name = application.Name
            };
        }

        public static Application Map(this ApplicationView application)
        {
            return new Application
            {
                VkAppId = application.Id,
                Name = application.Name
            };
        }
    }
}

VkApp.Web/Controllers/PasswordsController.cs
using System.Web.Mvc;
using VkApp.Data;
using VkApp.Data.DataProviders;

namespace VkApp.Web.Controllers
{
    [Authorize(Roles = Role.Admin)]
    public class PasswordsController: Controller
    {
        private readonly IUserRolesProvider _userRolesProvider;

        public PasswordsController(IUserRolesProvider userRolesProvider)
        {
            _userRolesProvider = userRolesProvider;
        }

        public ActionResult Index()
        {
            var roles = _userRolesProvider.GetUserRoles();

            return View("Index", roles);
        }

        public ActionResult Remove(int id)
        {
            _userRolesProvider.Remove(id);

            return RedirectToAction("Index");
        }

        public ActionResult Create(string password, string comment, bool allowMessages, bool allowInvites, bool allowFindFriends, bool allowInstruments)
        {
            if (string.IsNullOrEmpty(password))
            {
                ViewBag.AddPasswordError = "Password should not be empty";
                return Index();
            }

            _userRolesProvider.AddUserPassword(password, comment, allowMessages, allowInvites, allowFindFriends, allowInstruments);

            return RedirectToAction("Index");
        }
    }
}

VkApp.Web/Views/Admin/Applications.cshtml
@model  VkApp.Web.Models.ApplicationsView
@{
    ViewBag.Title = "Applications";
}

<div class="panel">
    @Html.ActionLink("Admin", "Index", "Admin") > <label class="title">Applications</label>

    @if (!string.IsNullOrEmpty(@Model.Error))
    {
        <div class="row">
            <div class="summary fail visible">Error: @Model.Error</div>
        </div>
    }

    <div class="row">
        <table class="grid">
            <tr class="header">
                <td style="width: 100px">Id</td>
                <td style="width: 200px">Name</td>
                <td style="width: 100px">Actions</td>
            </tr>

            @foreach (var application in Model.Applications)
            {
                <tr>
                    <td><b>@application.Id</b></td>
                    <td><b>@application.Name</b></td>
                    <td>@Html.ActionLink("Remove", "RemoveApplication", new { id = application.Id })</td>
                </tr>
            }
        </table>
    </div>

    <br />
    <label class="title">Add application:</label>

    <div class="row">
        @using (Html.BeginForm("AddApplication", "Admin", FormMethod.Post))
        {
            <label>Application Id: </label>
            @Html.TextBoxFor(m => m.NewApplication.Id)
            <br />
            <label>Name: </label>
            @Html.TextBoxFor(m => m.NewApplication.Name)
            <br />

            <input type="submit" value="Add">
        }
    </div>
</div>

VkApp.Web/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Admin";
}

<div class="panel">
    <label class="title">Администрирование</label>

    <div class="row">
        @Html.ActionLink("Applications", "Applications")
    </div>

    <div class="row">
        @Html.ActionLink("Statistics", "Index", "Statistics")
    </div>
    <div class="row">
        @Html.ActionLink("Groups", "Index", "Groups")
    </div>
    <div class="row">
        @Html.ActionLink("User passwords", "Index", "Passwords")
    </div>
</div>