VkApp.Web/Controllers/TrainingController.cs
using System.Web.Mvc;

namespace VkApp.Web.Controllers
{
    public class TrainingController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult InstallExtension()
        {
            return View();
        }
    }
}

VkApp.Web/Views/App/Index.cshtml
@model  VkApp.Web.Models.AppView
@{
    ViewBag.Title = "VkApp";
}

<div id="vkApp">
    @Html.Partial("~/app/view/authenticationPanel/authenticationPanel.cshtml", Model)
    @Html.Partial("~/app/view/authenticationPanel/implicitFlowAuthenticationPanel.cshtml", Model)
    @Html.Partial("~/app/view/initializationPanel/initializationPanel.cshtml")
    @Html.Partial("~/app/view/appPanel/appPanel.cshtml")
</div>

<div id="addByUrlDialog" style="display:none">
    <label>Вставьте URL:</label>
    <input type="text" id="photoUrlInput" class="url-input" />
</div>

<div id="captchaDialog" style="display:none">
    <img class="captcha-img"></img>
    <input type="text" id="captchaInput" />
</div>

@section scripts {
    <script src="https://vk.com/js/api/openapi.js?159" type="text/javascript"></script>

    <script type="text/javascript">
        function checkExtension(permissions) {
            if (!permissions.allowMessages) {
                return;
            }

            if (!window.localStorage["sndallExtension"]) {
                window.location.href = "@Url.Action("InstallExtension", "Training")";
                return;
            }

            window.sndallExtension = JSON.parse(window.localStorage["sndallExtension"]);

            if (window.sndallExtension.version < @ChromeExtensions.Version) {
                window.location.href = "@Url.Action("InstallExtension", "Training")";
                return;
            }

            setTimeout(function() {
                    delete window.localStorage["sndallExtension"];
                },
                1000);
        }

        $(function () {
            var permissions = @Html.Raw(Model.PermissionsJson);
            checkExtension(permissions);
            new VkApp(@Model.ApplicationId, permissions);
        });
    </script>
}